services:
  - type: web
    name: counseling-clinic
    runtime: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: python app_clinic.py --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
    plan: free
